### ISSUE TITLE
ReForge Support?

### ISSUE THREAD

**Issue by boredafk** [gustproof/sd-webui-forge-style-components#3]

**Comment by boredafk** [comment]
It's Not working on Reforge

**Comment by boredafk** [comment]
Error loading script: main.py
    Traceback (most recent call last):
      File "/home/studio-lab-user/forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/studio-lab-user/forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/studio-lab-user/forge/extensions/sd-webui-forge-style-components/scripts/main.py", line 9, in <module>
        from lib_ipadapter_style.IPAdapterPlus import IPAdapterApply
      File "/home/studio-lab-user/forge/extensions/sd-webui-forge-style-components/lib_ipadapter_style/IPAdapterPlus.py", line 8, in <module>
        import ldm_patched.modules.utils
    ModuleNotFoundError: No module named 'ldm_patched'
